CONFIG_ZMK_POINTING=y
CONFIG_I2C=y
CONFIG_IQS5XX=y

# I2C 에러 로그 음소거 (트랙패드가 잠들 때 발생하는 에러 스팸 방지)
CONFIG_I2C_LOG_LEVEL_OFF=y

# 🔥 보조 기판(오른쪽)에서 마우스/트랙패드 신호를 중앙으로 보낼 수 있게 허용 🔥
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_SPLIT_BLE_ROLE_CENTRAL=n
