CONFIG_ZMK_KEYBOARD_NAME="Lily58Wireless"
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_SLEEP=y
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
# ZMK 구형 마우스 에뮬레이션 활성화 (Ahmed 드라이버 필수 조건)
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_POINTING=y

# 1. 딥 슬립 모드 켜기 (필수)
CONFIG_ZMK_SLEEP=y

# 2. 몇 분 뒤에 잘지 설정 (선택 사항, 밀리초 단위)
# 900000 = 15분 (기본값)
# 1800000 = 30분
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# 🔥 Nice!View 디스플레이 위젯 강제 활성화 (왼쪽 화면 살리기) 🔥
CONFIG_ZMK_WIDGET_BATTERY_STATUS=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y
CONFIG_ZMK_WIDGET_LAYER_STATUS=y
CONFIG_ZMK_WIDGET_WPM_STATUS=y

